### PR TITLE
PR for commit 904a46 & 98dcad 

### PR DESCRIPTION
**Pull request by liujuanLT**
904a46:improve several paths for onnx(); write processed images recursively in dst_dir
98dcad:modelzoo: improve ssd_mobilenetv2;

### CODE REVIEW

**Review by liujuanLT — COMMENTED** [review]
test ok

**Review by liujuanLT — COMMENTED** [review]
test ok

**Comment by liujuanLT** [comment]
ok

**Review by liujuanLT — COMMENTED** [review]
ok2

**Review by wangyuehy — APPROVED** [review]

**Pull request merged**
